name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # 不因单个任务失败而取消其他任务
      matrix:
        include:
          # macOS ARM64
          - os: macos-26
            build_script: pnpm run dist:mac:arm64
            artifact_name: macos-arm64
            artifact_path: 'dist/*.dmg'
          # macOS x64
          - os: macos-26
            build_script: pnpm run dist:mac:x64
            artifact_name: macos-x64
            artifact_path: 'dist/*.dmg'
          # Windows x64
          - os: windows-latest
            build_script: pnpm run dist:win:x64
            artifact_name: windows-x64
            artifact_path: 'dist/*-x64.exe'
          # Windows ARM64
          - os: windows-latest
            build_script: pnpm run dist:win:arm64
            artifact_name: windows-arm64
            artifact_path: 'dist/*-arm64.exe'
          # Linux x64
          - os: ubuntu-latest
            build_script: pnpm run dist:linux:x64
            artifact_name: linux-x64
            artifact_path: |-
              dist/*-x64.AppImage
              dist/*-x64.deb
          # Linux ARM64
          - os: ubuntu-latest
            build_script: pnpm run dist:linux:arm64
            artifact_name: linux-arm64
            artifact_path: |-
              dist/*-arm64.AppImage
              dist/*-arm64.deb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Electron App
        run: ${{ matrix.build_script }}
        env:
          GH_TOKEN: ${{ secrets.ATRIOR_TOKEN }}

      # 上传构建产物为 GitHub Actions artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
          retention-days: 1

  # 统一发布到 Release
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          prerelease: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.ATRIOR_TOKEN }}
